### ISSUE TITLE
Did not manage to sucessfully setup just by following README

### ISSUE THREAD

**Issue by Bachibouzouk** [in-RET/in.RET-EnSys-open-plan-GUI#6]
Hello,

Nice to see what you made from open-plan tool :) 

I am trying your tool out locally and I use this as an opportunity to provide you with feedback!

If I blindly follow the readme here is what I found out:
- The file `app/requirements/postgres.txt` does not exist

- `pip install -r app/requirements/requirements.txt` worked except for `psycopg2` installation, `psycopg2-binary` did work

- I personally find that only the main packages should be listed in a requirements file, not the dependent subpackages

- the file `app/dev_requirements.txt does not exist` 

- There is no mention of `pip install app/requirements/InRetEnsys-0.2a7-py3-none-any.whl` but it seems to be needed

- The file to perform initial setup is named `initial_setup.sh` and not `local_setup.sh`

- Within the `initial_setup.sh`, the command `python manage.py loaddata 'fixtures/multivector_fixture_inret.json'` did not work, but  `python manage.py loaddata 'fixtures/fixture.json'` did

It is not written explicitely (or at least I didn't find it out) how to deploy the simulation server and link it to the GUI

**Comment by Bachibouzouk** [comment]
For the simulation I tried setting up the fastapi server (although setup was also [not smooth](https://github.com/in-RET/inretensys-fastapi/issues/12) from following readme), I did manage to have it run locally (not with docker). But then the server had internal errors with the POST request `/uploadJson?username=&password=&docker=false`

```
  File "/$HOME/api/docker.py", line 15, in simulate_docker
    os.makedirs(pathOfDockerWorkDir)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
```

**Comment by Bachibouzouk** [comment]
I tried to setup the fastapi server with docker as well but it still did not work

**Comment by Bachibouzouk** [comment]
@pyrokar1993 - any idea what might be the problem here?

**Comment by pyrokar1993** [comment]
@Bachibouzouk in the FastAPI-Folder there is an .env-file with an absolute Path to your Gurobi-License file -- which should point to an mvs-license and also an absolute path to the data directory
<img width="757" alt="Bildschirmfoto 2024-04-23 um 09 51 49" src="https://github.com/in-RET/in.RET-EnSys-open-plan-GUI/assets/10503749/4987164e-e95d-4f29-ba51-6e82eef1232e">

**Comment by Bachibouzouk** [comment]
Thanks @pyrokar1993 

Maybe this is the problem as I don't have a Gurobi license! It is possible to set it to use cbc solver? Or Gurobi is assumed and something must be changed in the configuration?

**Comment by pyrokar1993** [comment]
Okay. If you want to change the solver you can check the views.py in the projects-folder. 
This is part of the GUI-Django.

<img width="515" alt="Bildschirmfoto 2024-04-23 um 10 48 15" src="https://github.com/in-RET/in.RET-EnSys-open-plan-GUI/assets/10503749/98b7e242-99cd-4ce7-a0a0-596952081631">
